Repository redhat-developer/vscode-extension-tester, pull requests merged in 2023-02, with the labels that each got.

#599 Improve project readme file
  KNOWN_ISSUES.md
  README.md
Labels: ready for review

#621 Fix invalid artefact screenshot path in GH Actions
  src/suite/mochaHooks.ts
Labels: review done

#625 Add function to get paused breakpoint
  locators/lib/1.37.0.ts
  page-objects/src/components/editor/Breakpoint.ts
  page-objects/src/components/editor/TextEditor.ts
  page-objects/src/index.ts
  page-objects/src/locators/locators.ts
  test/test-project/src/test/debug/debug-test.ts
Labels: ready for review

#636 Provide log warning when used vscode version differs from 'latest' version
  src/util/codeUtil.ts
Labels: ready for review

#635 Support for latest stable VSCode 1.75.x release
  .github/workflows/insiders.yml
  .github/workflows/main.yml
  page-objects/src/components/bottomBar/Views.ts
  src/extester.ts
  test/test-project/.vscode/settings.json
  test/test-project/package.json
  test/test-project/src/test/debug/debug-test.ts
  test/test-project/src/test/editor/editorView-test.ts
  test/test-project/src/test/editor/textEditor-test.ts
  test/test-project/src/test/menu/titleBar-test.ts
  test/test-project/src/test/statusBar/statusBar-test.ts
  test/test-project/src/test/workbench/input-test.ts
Labels: ready for review, prio

#609 Override WebElement.isSelected for EditorTab class
  page-objects/src/components/editor/EditorView.ts
  test/test-project/src/test/editor/editorView-test.ts
Labels: ready for review
