Repository redhat-developer/vscode-extension-tester, pull requests merged in 2023-01, with the labels that each got.

#549 Declare locators and page-objects as workspaces
  package-lock.json
  package.json
Labels: bug

#548 Enable dependabot for npm packages
  .github/dependabot.yml
Labels: skip-changelog

#565 Bump 'max' placeholder to vscode 1.74.2
  src/extester.ts
Labels: ready for review

#566 Flaky CustomTreeSection > getVisibleItems tests on macOS
  .github/workflows/mac.yml
  page-objects/src/components/sidebar/tree/custom/CustomTreeSection.ts
  test/test-project/.gitignore
  test/test-project/.vscodeignore
  test/test-project/package.json
  test/test-project/src/test/xsideBar/customView-test.ts
Labels: ready for review

#572 Configure dependabot to increase version in requirements
  .github/dependabot.yml
Labels: skip-changelog

#574 Revert "Bump got from 11.8.6 to 12.5.3"
  package-lock.json
  package.json
Labels: dependencies, skip-changelog, prio

#573 Cancel in-progress builds if a PR is updated
  .github/workflows/insiders.yml
  .github/workflows/linux.yml
  .github/workflows/mac.yml
  .github/workflows/windows.yml
Labels: skip-changelog

#576 Bump 'max' placeholder to latest vscode 1.74.3
  src/extester.ts
Labels: bug, ready for review

#580 Enable npm package caching
  .github/workflows/insiders.yml
  .github/workflows/linux.yml
  .github/workflows/mac.yml
  .github/workflows/windows.yml
Labels: skip-changelog

#595 Solve warnings about used deprecated dependencies
  package-lock.json
  package.json
Labels: dependencies, ready for review, skip-changelog

#596 Provide only one specific CI workflow for main branch
  .github/workflows/linux.yml
  .github/workflows/mac.yml
  .github/workflows/main.yml
  .github/workflows/windows.yml
  README.md
Labels: ready for review, skip-changelog

#594 Cannot use WebView.switchToFrame() with VSCode 1.74+ when there are several webview opened
  page-objects/src/components/editor/WebView.ts
  test/test-project/src/extension.ts
  test/test-project/src/test/editor/editorView-test.ts
  test/test-project/src/test/editor/webView-test.ts
Labels: ready for review, prio

#607 Fix upload artifact step of main workflow to work for all runners
  .github/workflows/main.yml
  test/test-project/package.json
Labels: ready for review

#597 Improve Insiders CI workflow
  .github/workflows/insiders.yml
Labels: ready for review
