Repository redhat-developer/vscode-extension-tester, pull requests merged in 2023-03, with the labels that each got.

#675 Bump 'max' placeholder to latest vscode 1.76.1
  .github/workflows/main.yml
  src/extester.ts
Labels: prio

#679 Run all possible tests also on macOS
  .github/workflows/insiders.yml
  .github/workflows/main.yml
  page-objects/src/components/bottomBar/Views.ts
  page-objects/src/components/editor/ContentAssist.ts
  page-objects/src/components/editor/EditorView.ts
  page-objects/src/components/editor/TextEditor.ts
  page-objects/src/components/workbench/Workbench.ts
  test/test-project/package.json
  test/test-project/src/test/bottomBar/bottomBarPanel-test.ts
  test/test-project/src/test/bottomBar/problemsView-test.ts
  test/test-project/src/test/bottomBar/views-test.ts
  test/test-project/src/test/debug/debug-test.ts
  test/test-project/src/test/editor/editorView-test.ts
  test/test-project/src/test/editor/settingsEditor-test.ts
  test/test-project/src/test/editor/textEditor-test.ts
  test/test-project/src/test/menu/macTitleBar-test.ts
  test/test-project/src/test/workbench/workbench-test.ts
  test/test-project/src/test/xsideBar/scmView-test.ts
  test/test-project/vscode-settings.json
Labels: ready for review

#693 Bump 'max' placeholder to latest vscode 1.76.2
  src/extester.ts
Labels: prio

#670 Allow to consume multiple strings blob as extester cli arg
  src/cli.ts
  src/extester.ts
  src/suite/runner.ts
  src/util/codeUtil.ts
  test/test-project/package.json
  test/test-project/src/test/cli/order-1-test.ts
  test/test-project/src/test/cli/order-2-test.ts
  test/test-project/src/test/cli/order-3-test.ts
Labels: enhancement, ready for review

#715 Use vsce API instead CLI
  src/extester.ts
  src/util/codeUtil.ts
Labels: ready for review
