Repository redhat-developer/vscode-extension-tester, pull requests merged in 2024-11, with the labels that each got.

#1605 feat: bump vscode-max from 1.95.0 to 1.95.1
  packages/extester/package.json
Labels: enhancement

#1613 fix(test): failing Debug Session > TextEditor: getBreakpoints test
  tests/test-project/src/test/debug/debug.test.ts
Labels: task

#1584 feat(cli): This change allows to install pre-release version of the extensions to the test instance when available in the marketplace
  docs/Test-Setup.md
  packages/extester/src/cli.ts
  packages/extester/src/extester.ts
  packages/extester/src/util/codeUtil.ts
Labels: enhancement

#1618 feat: bump vscode-max from 1.95.1 to 1.95.2
  packages/extester/package.json
Labels: enhancement

#1617 feat: add Watch section support
  docs/DebugView.md
  docs/images/debugView-CallStack.png
  docs/images/debugView-Variables.png
  docs/images/debugView-WatchSection.png
  packages/locators/lib/1.37.0.ts
  packages/page-objects/src/components/sidebar/debug/DebugView.ts
  packages/page-objects/src/components/sidebar/tree/debug/WatchSection.ts
  packages/page-objects/src/components/sidebar/tree/debug/WatchSectionItem.ts
  packages/page-objects/src/index.ts
  packages/page-objects/src/locators/locators.ts
  tests/test-project/src/test/debug/debug.test.ts
Labels: enhancement, ready-for-review

#1633 feat: bump vscode-max from 1.95.2 to 1.95.3
  packages/extester/package.json
Labels: enhancement
