Repository redhat-developer/vscode-extension-tester, pull requests merged in 2024-10, with the labels that each got.

#1527 feat: Add support for Extension Editor View
  docs/ExtensionEditorDetailsSections.md
  docs/ExtensionEditorView.md
  packages/locators/lib/1.37.0.ts
  packages/page-objects/src/components/editor/ExtensionEditorDetailsSection.ts
  packages/page-objects/src/components/editor/ExtensionEditorView.ts
  packages/page-objects/src/index.ts
  packages/page-objects/src/locators/locators.ts
  tests/test-project/src/test/editor/extensionEditor.test.ts
Labels: enhancement, ready-for-review

#1548 feat: change waitForBreakPoint timeout datatype
  packages/page-objects/src/components/workbench/DebugToolbar.ts
Labels: enhancement

#1551 feat: bump vscode-max from 1.93.1 to 1.94.0
  .github/workflows/main.yml
  README.md
  packages/extester/package.json
  tests/test-project/src/test/bottomBar/problemsView.test.ts
Labels: enhancement

#1558 feat: upgrade ESLint to version 9
  .eslintrc.json
  eslint.config.js
  package-lock.json
  package.json
  packages/extester/package.json
  packages/extester/src/suite/mochaHooks.ts
  packages/locators/package.json
  packages/page-objects/package.json
  tests/test-project/package.json
  tests/test-project/src/catScratchEditor.ts
  tsconfig.json
Labels: enhancement, ready-for-review

#1577 docs: move example project to different repository
  README.md
  docs/Debugging-Tests.md
  docs/Writing-Simple-Tests.md
  examples/helloworld-extester/.eslintrc.json
  examples/helloworld-extester/.gitignore
  examples/helloworld-extester/.mocharc.js
  examples/helloworld-extester/.vscode/launch.json
  examples/helloworld-extester/.vscode/tasks.json
  examples/helloworld-extester/.vscodeignore
  examples/helloworld-extester/LICENSE
  examples/helloworld-extester/README.md
  examples/helloworld-extester/demo.gif
  examples/helloworld-extester/icons/logo.png
  examples/helloworld-extester/package-lock.json
  examples/helloworld-extester/package.json
  examples/helloworld-extester/settings.json
  examples/helloworld-extester/src/extension.ts
  examples/helloworld-extester/src/ui-test/.mocharc-debug.js
  examples/helloworld-extester/src/ui-test/activityBar.test.ts
  examples/helloworld-extester/src/ui-test/bottomBar.test.ts
  examples/helloworld-extester/src/ui-test/commands.test.ts
  examples/helloworld-extester/src/ui-test/extensionsView.test.ts
  examples/helloworld-extester/src/ui-test/input.test.ts
  examples/helloworld-extester/src/ui-test/menus.test.ts
  examples/helloworld-extester/src/ui-test/modalDialog.test.ts
  examples/helloworld-extester/src/ui-test/notifications.test.ts
  examples/helloworld-extester/src/ui-test/resources/problems.ts
  examples/helloworld-extester/src/ui-test/resources/test/test-file
  examples/helloworld-extester/src/ui-test/resources/test/test-folder/more-test-file
  examples/helloworld-extester/src/ui-test/settingsEditor.test.ts
  examples/helloworld-extester/src/ui-test/statusBar.test.ts
  examples/helloworld-extester/src/ui-test/textEditor.test.ts
  examples/helloworld-extester/src/ui-test/treeView.test.ts
  examples/helloworld-extester/src/ui-test/webView.test.ts
  examples/helloworld-extester/tsconfig.json
Labels: ready-for-review

#1578 build(deps): bump got from 13.0.0 to 14.4.3
  package-lock.json
  packages/extester/package.json
Labels: dependencies, javascript

#1576 feat: bump vscode-max from 1.94.0 to 1.94.2
  packages/extester/package.json
Labels: enhancement

#1598 feat: bump vscode-max from 1.94.2 to 1.95.0
  .github/workflows/main.yml
  README.md
  packages/extester/package.json
Labels: enhancement
