Repository redhat-developer/vscode-extension-tester, pull requests merged in 2024-08, with the labels that each got.

#1470 fix: getQuickPicks and isSelected does not work as expected
  packages/locators/lib/1.37.0.ts
  packages/page-objects/src/components/workbench/input/Input.ts
  packages/page-objects/src/locators/locators.ts
  tests/test-project/src/test/workbench/input.test.ts
Labels: bug, ready-for-review

#1460 feat: bump vscode-max from 1.91.1 to 1.92.1
  .github/workflows/main.yml
  README.md
  packages/extester/package.json
  tests/test-project/src/test/bottomBar/bottomBarPanel.test.ts
Labels: enhancement

#1485 fix: webView findWebElement returning undefined
  packages/locators/lib/1.90.0.ts
  tests/test-project/src/extension.ts
  tests/test-project/src/test/webview/webView.test.ts
  tests/test-project/src/test/webview/webviewView.test.ts
Labels: bug

#1487 feat: bump vscode-max from 1.92.1 to 1.92.2
  packages/extester/package.json
Labels: enhancement

#1503 feat: Add TextEditor.getBreakpoints(): Promise<Breakpoint[]>
  packages/page-objects/src/components/editor/TextEditor.ts
  tests/test-project/src/test/debug/debug.test.ts
Labels: enhancement, ready-for-review
