Repository redhat-developer/vscode-extension-tester, pull requests merged in 2025-02, with the labels that each got.

#1733 fix: address comparison for version string
  packages/extester/src/browser.ts
  packages/page-objects/src/components/activityBar/ViewControl.ts
  packages/page-objects/src/components/bottomBar/AbstractViews.ts
  packages/page-objects/src/components/editor/SettingsEditor.ts
  packages/page-objects/src/components/editor/TextEditor.ts
  packages/page-objects/src/components/sidebar/debug/DebugView.ts
  packages/page-objects/src/components/sidebar/scm/NewScmView.ts
  packages/page-objects/src/components/sidebar/tree/debug/VariableSectionItem.ts
  packages/page-objects/src/components/workbench/Notification.ts
  packages/page-objects/src/components/workbench/Workbench.ts
  tests/test-project/src/test/bottomBar/views.test.ts
  tests/test-project/src/test/debug/debug.test.ts
  tests/test-project/src/test/dialog/dialog.test.ts
  tests/test-project/src/test/editor/diffEditor.test.ts
  tests/test-project/src/test/editor/editorView.test.ts
  tests/test-project/src/test/editor/extensionEditor.test.ts
  tests/test-project/src/test/statusBar/statusBar.test.ts
  tests/test-project/src/test/workbench/input.test.ts
  tests/test-project/src/test/workbench/notifications.test.ts
  tests/test-project/src/test/xsideBar/scmView.test.ts
  tests/test-project/src/test/xsideBar/sideBarView.test.ts
  tests/test-project/src/test/xsideBar/xtensionsView.test.ts
Labels: bug

#1753 feat: add support for VS Code 1.97
  .github/workflows/main.yml
  README.md
  docs/ViewSection.md
  packages/extester/package.json
  packages/locators/lib/1.37.0.ts
  packages/page-objects/src/components/sidebar/ViewSection.ts
  packages/page-objects/src/locators/locators.ts
Labels: enhancement

#1757 feat: Provide WelcomeContentSection.getButton
  docs/CustomTreeSection.md
  packages/page-objects/src/components/sidebar/WelcomeContent.ts
  tests/test-project/src/test/xsideBar/customView.test.ts
Labels: enhancement

#1756 chore(release): Publish 8.12.0
  package-lock.json
  packages/extester/package.json
  packages/locators/package.json
  packages/page-objects/package.json
Labels: skip-changelog

#1782 feat: Support ViewSection dropdown menu actions
  docs/ViewSection.md
  docs/images/viewActions-dropdown.png
  packages/page-objects/src/components/ActionButtonElementDropdown.ts
  packages/page-objects/src/components/editor/EditorAction.ts
  packages/page-objects/src/components/sidebar/ViewSection.ts
  tests/test-project/package.json
  tests/test-project/src/test/xsideBar/customView.test.ts
Labels: enhancement
