Repository redhat-developer/vscode-extension-tester, pull requests merged in 2025-06, with the labels that each got.

#1911 feat: add support for readme in ExtensionEditorDetailsSection
  packages/locators/lib/1.37.0.ts
  packages/page-objects/src/components/editor/ExtensionEditorDetailsSection.ts
  packages/page-objects/src/locators/locators.ts
  tests/test-project/src/test/editor/extensionEditor.test.ts
Labels: enhancement

#1872 chore: reformat code when using vscode
  .vscode/extensions.json
  .vscode/settings.json
Labels: review-done

#1859 chore: filter unsupported NODE_* variables when calling VS Code
  package.json
  packages/extester/src/util/codeUtil.ts
Labels: review-done

#1915 chore(deps): security patch for tar-fs
  package-lock.json
Labels: dependencies, javascript

#1914 fix: InputBox.selectQuickPick is not working properly for File/Folder picker
  packages/page-objects/src/components/workbench/input/Input.ts
  tests/test-project/src/test/workbench/input.test.ts
Labels: bug

#1857 feat: allow download to disable tls check env flag
  docs/Test-Setup.md
  packages/extester/src/util/download.ts
Labels: enhancement, review-done

#1933 feat: provide a timeout for EditorView.getAction
  packages/page-objects/src/components/editor/EditorView.ts
Labels: enhancement, ready-for-review
