Repository redhat-developer/vscode-extension-tester, pull requests merged in 2025-01, with the labels that each got.

#1700 chore(ci): Switch pipeline back to ubuntu-latest
  .github/workflows/template-main.yaml
Labels: ready-for-review, task

#1697 feat: BottomBarPanel support for custom tabs
  docs/BottomBarPanel.md
  packages/page-objects/src/components/bottomBar/BottomBarPanel.ts
  tests/test-project/src/test/bottomBar/bottomBarPanel.test.ts
  tests/test-project/src/test/webview/webviewView.test.ts
Labels: enhancement, ready-for-review

#1708 feat: bump vscode-max from 1.96.2 to 1.96.3
  packages/extester/package.json
Labels: enhancement

#1714 chore(ci): Group eslint for dependabot upgrades
  .github/dependabot.yml
Labels: ready-for-review, task

#1717 fix: use specified test directory for temporary folders
  packages/extester/src/util/codeUtil.ts
Labels: bug, ready-for-review
