Repository redhat-developer/vscode-extension-tester, pull requests merged in 2025-04, with the labels that each got.

#1769 chore: remove unused variables for webview locator
  packages/locators/lib/1.37.0.ts
  packages/locators/lib/1.74.0.ts
  packages/page-objects/src/locators/locators.ts
Labels: task

#1800 fix: Support arm64 on windows
  packages/extester/src/util/codeUtil.ts
Labels: bug

#1835 feat: Add support for VS Code 1.99
  .github/workflows/main.yml
  README.md
  package-lock.json
  package.json
  packages/extester/package.json
  packages/locators/lib/1.99.0.ts
  tests/test-project/package.json
  tests/test-project/src/test/webview/webView.test.ts
Labels: enhancement
